### ISSUE TITLE
Incompatible with WebStorm v2022.2

### ISSUE THREAD

**Issue by nessor** [KartanHQ/intellij-nextjs#101]
**Describe the bug**
The plugin seems to be incompatible with WebStorm 2022.2.

![image](https://user-images.githubusercontent.com/3463261/181751615-f8fb050c-b510-49ad-923f-ea9306c59947.png)

**To Reproduce**
1. Install WebStorm 2022.1
2. Install the plugin
3. Upgrade to WebStorm 2022.2
(4. Open settings > Plugins > Next.js)

**Additional context**
Installed WebStorm build where the problem appears: 222.3345.108

**Comment by nekofar** [comment]
It's going to be available on the marketplace in a couple of hours.

**Comment by nessor** [comment]
Cool! Thank you :) Appreciate your work!
