### ISSUE TITLE
Update from WebStorm team

### ISSUE THREAD

**Issue by anstarovoyt** [KartanHQ/intellij-nextjs#111]
Hi! First of all, thank you for the plugin! It helped a lot of users. 

I want to tell you that started from 2022.3 we are going to introduce own Next.js project generator as a part WebStorm, since we plan to deprecated some existing generators and add more new generators for modern technologies (including vite and Next.js).

It is JFYI: no actions required from you side.

**Comment by nekofar** [comment]
I'm glad to hear that my work helped people;  Thank you for letting me know.
