### ISSUE TITLE
Add support for release 2022.3

### ISSUE THREAD

**Issue by pitgrap** [KartanHQ/intellij-nextjs#203]
Only version 2022.2 (222.\*) is supported. Please increase the supported version to 2022.3 (223.\*)

See https://github.com/KartanHQ/intellij-nextjs/blob/master/gradle.properties#L13

**Comment by nekofar** [comment]
> Only version 2022.2 (222.*) is supported. Please increase the supported version to 2022.3 (223.*)
> 
> See https://github.com/KartanHQ/intellij-nextjs/blob/master/gradle.properties#L13

I kept it intentionally for older versions. Since version 2022.3, there is an official Next.js plugin available by JetBrains team. (#111)

**Comment by xtrasmal** [comment]
@nekofar will be uninstalling later on. Thanks for the plugin. 🍺
