### ISSUE TITLE
Allow usage of yarn as a package manager

### ISSUE THREAD

**Issue by otomir23** [KartanHQ/intellij-nextjs#45]
#### The problem.
Currently you can only use `npx create-next-app` to create a new project. This is a problem because some pepole _(including me)_ prefer `yarn` over `npm`, and reconfiguring the project is more time-consuming than just creating it using terminal instead of IDE.

#### Solution.
Add the ability to choose `yarn` as a package manager, either by allowing `yarn create next-app` in **Create Next App** field, either by making a dropdown to choose.

**Comment by nekofar** [comment]
Thank you for the suggestion; I think I could do something about that. I'll look into that.

**Comment by ducan-ne** [comment]
Please support pnpm too

**Comment by Cliftonz** [comment]
Agree, that yarn should be supported too.

**Comment by otomir23** [comment]
How's the progress on this?

**Comment by Cliftonz** [comment]
This is incorrect, this should still remain open.

**Comment by otomir23** [comment]
nuh uh
